version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_simple_crm
    environment:
      MYSQL_ROOT_PASSWORD: dinhthai2004  # Đặt mật khẩu cho người dùng root
      MYSQL_DATABASE: simple_crm               # Tạo database mặc định
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pdinhthai2004 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

      
  web:
    image: theodorescsa/ezpdf-lib-requirements:latest
    container_name: simple_crm
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
     
    env_file:
      - .env  # Thêm dòng này để container nhận các biến môi trường từ file .env

    volumes:
      - .:/app

    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py shell < create_superuser.py &&
        python manage.py runserver 0.0.0.0:8000"

    restart: unless-stopped

volumes:
  db_data:

